export const PLATFORM = {
  OVERVIEW: '/platform/overview',
  METRICS: '/platform/metrics',
  NOTIFICATION_DISPATCHES: '/platform/notification-dispatches',
  NOTIFICATION_DISPATCH: (id: number) => `/platform/notification-dispatches/${id}`,
  NOTIFICATION_DISPATCHES_BULK_DELETE: '/platform/notification-dispatches/bulk-delete',
  BUSINESSES: '/platform/businesses',
  BUSINESS_STATS: '/platform/businesses/stats',
  BUSINESS_STATUS: (id: number) => `/platform/businesses/${id}/status`,
  BUSINESS_DELETE: (id: number) => `/platform/businesses/${id}`,
  BUSINESS_RESET_DATA: (id: number) => `/platform/businesses/${id}/reset-data`,
  BUSINESSES_BULK_DELETE: '/platform/businesses/bulk-delete',
  BUSINESSES_BULK_STATUS: '/platform/businesses/bulk-status',
  BUSINESSES_NOTIFY: '/platform/businesses/notify',
  BUSINESS_SUBSCRIPTION_ACTIVATE: (id: number) => `/platform/businesses/${id}/subscription`,
  USERS: '/platform/users',
  USER_STATS: '/platform/users/stats',
  CONVERSIONS: '/platform/conversions',
  USER_STATUS: (id: number) => `/platform/users/${id}/status`,
  USER_PRIVILEGES: (id: number) => `/platform/users/${id}/privileges`,
  USER_DELETE: (id: number) => `/platform/users/${id}`,
  USERS_BULK_DELETE: '/platform/users/bulk-delete',
  USERS_BULK_ASSIGN_ROLES: '/platform/users/bulk-assign-roles',
  USERS_BULK_STATUS: '/platform/users/bulk-status',
  USERS_BULK_PRIVILEGES: '/platform/users/bulk-privileges',
  USERS_NOTIFY: '/platform/users/notify',
  ROLES: '/platform/roles',
  ROLE: (id: number) => `/platform/roles/${id}`,
  ROLE_MEMBERS: (id: number) => `/platform/roles/${id}/members`,
  PERMISSIONS: '/platform/permissions',
  CAMPAIGN_CODES: '/platform/referral-codes',
  CAMPAIGN_CODE: (id: number) => `/platform/referral-codes/${id}`,
  CAMPAIGN_CODE_USAGE: (id: number) => `/platform/referral-codes/${id}/usage`,
  PAYOUTS: {
    PAYABLES: '/platform/payouts/payables',
    BASE: '/platform/payouts',
    HISTORY: '/platform/payouts/history',
    SCHEDULE: '/platform/payouts/schedule',
    CANCEL: (id: number) => `/platform/payouts/${id}/cancel`,
  },
  GUIDE: {
    TUTORIALS: '/platform/guide/tutorials',
    TUTORIAL: (id: number) => `/platform/guide/tutorials/${id}`,
    TUTORIALS_PREVIEW_THUMB: '/platform/guide/tutorials/preview-thumbnail',
    TUTORIALS_UPLOAD_PENDING: '/platform/guide/tutorials/upload-thumbnail-pending',
    TUTORIAL_UPLOAD_THUMB: (id: number) => `/platform/guide/tutorials/${id}/upload-thumbnail`,
    FAQS: '/platform/guide/faqs',
    FAQ: (id: number) => `/platform/guide/faqs/${id}`,
    FEEDBACK: '/platform/guide/feedback',
    FEEDBACK_ITEM: (id: number) => `/platform/guide/feedback/${id}`,
    FEEDBACK_BULK_DELETE: '/platform/guide/feedback/bulk-delete',
  },
} as const;
