export const PLATFORM = {
  OVERVIEW: '/platform/overview',
  METRICS: '/platform/metrics',
  BUSINESSES: '/platform/businesses',
  BUSINESS_STATS: '/platform/businesses/stats',
  BUSINESS_STATUS: (id: number) => `/platform/businesses/${id}/status`,
  BUSINESS_DELETE: (id: number) => `/platform/businesses/${id}`,
  BUSINESSES_BULK_DELETE: '/platform/businesses/bulk-delete',
  BUSINESSES_BULK_STATUS: '/platform/businesses/bulk-status',
  BUSINESSES_NOTIFY: '/platform/businesses/notify',
  USERS: '/platform/users',
  USER_STATS: '/platform/users/stats',
  USER_STATUS: (id: number) => `/platform/users/${id}/status`,
  USER_DELETE: (id: number) => `/platform/users/${id}`,
  USERS_BULK_DELETE: '/platform/users/bulk-delete',
  USERS_BULK_ASSIGN_ROLES: '/platform/users/bulk-assign-roles',
  USERS_BULK_STATUS: '/platform/users/bulk-status',
  USERS_NOTIFY: '/platform/users/notify',
  ROLES: '/platform/roles',
  ROLE: (id: number) => `/platform/roles/${id}`,
  PERMISSIONS: '/platform/permissions',
  GUIDE: {
    TUTORIALS: '/platform/guide/tutorials',
    TUTORIAL: (id: number) => `/platform/guide/tutorials/${id}`,
    TUTORIALS_PREVIEW_THUMB: '/platform/guide/tutorials/preview-thumbnail',
    TUTORIALS_UPLOAD_PENDING: '/platform/guide/tutorials/upload-thumbnail-pending',
    TUTORIAL_UPLOAD_THUMB: (id: number) => `/platform/guide/tutorials/${id}/upload-thumbnail`,
    FAQS: '/platform/guide/faqs',
    FAQ: (id: number) => `/platform/guide/faqs/${id}`,
    FEEDBACK: '/platform/guide/feedback',
    FEEDBACK_ITEM: (id: number) => `/platform/guide/feedback/${id}`,
    FEEDBACK_BULK_DELETE: '/platform/guide/feedback/bulk-delete',
  },
} as const;
