export const HR = {
  DEPARTMENTS: '/hr/departments',
  DEPARTMENT: (id: number) => `/hr/departments/${id}`,
  POSITIONS: '/hr/positions',
  POSITION: (id: number) => `/hr/positions/${id}`,
  EMPLOYEES: '/hr/employees',
  EMPLOYEES_WITH_ACCOUNT: '/hr/employees/with-account',
  EMPLOYEES_SYNC_STAFF: '/hr/employees/sync-staff',
  ACCOUNT_OPTIONS: '/hr/account-options',
  EMPLOYEE: (id: number) => `/hr/employees/${id}`,
  EMPLOYEE_LINK_USER: (id: number) => `/hr/employees/${id}/link-user`,
  EMPLOYEE_UNLINK_USER: (id: number) => `/hr/employees/${id}/unlink-user`,
  EMPLOYEE_CREATE_ACCOUNT: (id: number) => `/hr/employees/${id}/create-account`,
  EMPLOYEE_REMOVE_ACCOUNT: (id: number) => `/hr/employees/${id}/remove-account`,
  ATTENDANCE_CLOCK: '/hr/attendance/clock',
  ATTENDANCE_EVENTS: '/hr/attendance/events',
  ATTENDANCE_REGISTER: '/hr/attendance/register',
  ATTENDANCE_DAYS: '/hr/attendance/days',
  ATTENDANCE_IMPORT_TIMESHEETS: '/hr/attendance/import-timesheets',
  ATTENDANCE_SHIFTS: '/hr/attendance/pos-shifts',
  LEAVE_TYPES: '/hr/leave/types',
  LEAVE_TYPE: (id: number) => `/hr/leave/types/${id}`,
  LEAVE_BALANCES: '/hr/leave/balances',
  LEAVE_BALANCES_ENSURE: '/hr/leave/balances/ensure',
  LEAVE_REQUESTS: '/hr/leave/requests',
  LEAVE_REQUEST_APPROVE: (id: number) => `/hr/leave/requests/${id}/approve`,
  LEAVE_REQUEST_REJECT: (id: number) => `/hr/leave/requests/${id}/reject`,
  LEAVE_REQUEST_CANCEL: (id: number) => `/hr/leave/requests/${id}/cancel`,
  SALARY_STRUCTURES: '/hr/payroll/structures',
  SALARY_STRUCTURE: (id: number) => `/hr/payroll/structures/${id}`,
  COMPENSATIONS: '/hr/payroll/compensations',
  COMPENSATION: (id: number) => `/hr/payroll/compensations/${id}`,
  PAY_RUNS: '/hr/payroll/pay-runs',
  PAY_RUN: (id: number) => `/hr/payroll/pay-runs/${id}`,
  PAY_RUN_CALCULATE: (id: number) => `/hr/payroll/pay-runs/${id}/calculate`,
  PAY_RUN_APPROVE: (id: number) => `/hr/payroll/pay-runs/${id}/approve`,
  PAY_RUN_POST: (id: number) => `/hr/payroll/pay-runs/${id}/post`,
  PAY_RUN_SETTLE: (id: number) => `/hr/payroll/pay-runs/${id}/settle`,
  PAY_RUN_REMIT_STATUTORY: (id: number) => `/hr/payroll/pay-runs/${id}/remit-statutory`,
  PAY_RUN_VOID: (id: number) => `/hr/payroll/pay-runs/${id}/void`,
  ONBOARDING_TEMPLATES: '/hr/talent/onboarding-templates',
  ONBOARDING_TEMPLATE: (id: number) => `/hr/talent/onboarding-templates/${id}`,
  ONBOARDING_ASSIGN: '/hr/talent/onboarding/assign',
  ONBOARDING_TASKS: '/hr/talent/onboarding-tasks',
  ONBOARDING_TASK: (id: number) => `/hr/talent/onboarding-tasks/${id}`,
  REVIEWS: '/hr/talent/reviews',
  REVIEW: (id: number) => `/hr/talent/reviews/${id}`,
  PERFORMANCE: '/hr/talent/performance',
  PERFORMANCE_EMPLOYEE: (employeeId: number) => `/hr/talent/performance/employees/${employeeId}`,
  PERFORMANCE_BY_USER: (userId: number) => `/hr/talent/performance/by-user/${userId}`,
  PERFORMANCE_SEED_REVIEW: (employeeId: number) => `/hr/talent/performance/employees/${employeeId}/seed-review`,
  REPORTS_PAYE: '/hr/reports/paye-schedule',
  REPORTS_NSSF: '/hr/reports/nssf-schedule',
  AUDIT_LOGS: '/hr/audit-logs',
} as const;
