export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  PRICING: '/pricing',
  PRIVACY: '/privacy',
  DASHBOARD: '/dashboard',
  SALES: { INDEX: '/sales', NEW: '/sales/new', HISTORY: '/sales/history', REFUNDS: '/sales/refunds', MY_SHIFT: '/sales/my-shift' },
  INVENTORY: { INDEX: '/inventory', PRODUCTS: '/inventory/products', CATEGORIES: '/inventory/categories', STOCK: '/inventory/stock' },
  CUSTOMERS: { INDEX: '/customers' },
  EXPENSES: { INDEX: '/expenses', CATEGORIES: '/expenses/categories', LIST: '/expenses/list' },
  SETTINGS: { INDEX: '/settings', BUSINESS: '/settings/business', PROFILE: '/settings/profile', STAFF: '/settings/staff', ROLES: '/settings/roles', SUBSCRIPTION: '/settings/subscription' },
  PLATFORM: {
    INDEX: '/platform',
    OVERVIEW: '/platform/overview',
    BUSINESSES: '/platform/businesses',
    USERS: '/platform/users',
    TEAM: '/platform/team',
  },
} as const;
