export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  PRICING: '/pricing',
  PRIVACY: '/privacy',
  DASHBOARD: '/dashboard',
  SALES: { INDEX: '/sales', NEW: '/sales/new', HISTORY: '/sales/history', REFUNDS: '/sales/refunds', MY_SHIFT: '/sales/my-shift' },
  INVENTORY: { INDEX: '/inventory', PRODUCTS: '/inventory/products', CATEGORIES: '/inventory/categories', STOCK: '/inventory/stock' },
  CUSTOMERS: { INDEX: '/customers' },
  EXPENSES: { INDEX: '/expenses', CATEGORIES: '/expenses/categories', LIST: '/expenses/list' },
  ACCOUNT: {
    INDEX: '/account',
    NOTIFICATIONS: '/account/notifications',
    PROFILE: '/account/profile',
  },
  NOTIFICATIONS: { INDEX: '/account/notifications' },
  GUIDE: {
    INDEX: '/guide',
    TUTORIALS: '/guide/tutorials',
    FAQS: '/guide/faqs',
    FEEDBACK: '/guide/feedback',
  },
  SETTINGS: { INDEX: '/settings', BUSINESS: '/settings/business', STAFF: '/settings/staff', ROLES: '/settings/roles', SUBSCRIPTION: '/settings/subscription' },
  PLATFORM: {
    INDEX: '/platform',
    OVERVIEW: '/platform/overview',
    BUSINESSES: '/platform/businesses',
    USERS: '/platform/users',
    ROLES: '/platform/roles',
    GUIDE: {
      INDEX: '/platform/guide',
      TUTORIALS: '/platform/guide/tutorials',
      FAQS: '/platform/guide/faqs',
      FEEDBACK: '/platform/guide/feedback',
    },
  },
} as const;
