export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  PRICING: '/pricing',
  PRIVACY: '/privacy',
  DASHBOARD: '/dashboard',
  SALES: { INDEX: '/sales', NEW: '/sales/new', HISTORY: '/sales/history', REFUNDS: '/sales/refunds', MY_SHIFT: '/sales/my-shift' },
  INVENTORY: { INDEX: '/inventory', PRODUCTS: '/inventory/products', CATEGORIES: '/inventory/categories', STOCK: '/inventory/stock' },
  CUSTOMERS: { INDEX: '/customers' },
  INVOICES: { INDEX: '/invoices', NEW: '/invoices/new', DETAIL: (id: number) => `/invoices/${id}` },
  EXPENSES: { INDEX: '/expenses', CATEGORIES: '/expenses/categories', LIST: '/expenses/list' },
  ACCOUNT: {
    INDEX: '/account',
    NOTIFICATIONS: '/account/notifications',
    PROFILE: '/account/profile',
  },
  NOTIFICATIONS: { INDEX: '/account/notifications' },
  GUIDE: {
    INDEX: '/guide',
    TUTORIALS: '/guide/tutorials',
    FAQS: '/guide/faqs',
    FEEDBACK: '/guide/feedback',
    CONTACT: '/guide/contact',
  },
  SETTINGS: { INDEX: '/settings', BUSINESS: '/settings/business', TAX: '/settings/tax', STAFF: '/settings/staff', ROLES: '/settings/roles', SUBSCRIPTION: '/settings/subscription' },
  ACCOUNTING: {
    INDEX: '/accounting',
    STATEMENTS: '/accounting/statements',
    CHART_OF_ACCOUNTS: '/accounting/chart-of-accounts',
    JOURNAL_ENTRIES: '/accounting/journal-entries',
    TRIAL_BALANCE: '/accounting/trial-balance',
    INCOME_STATEMENT: '/accounting/income-statement',
    BALANCE_SHEET: '/accounting/balance-sheet',
    RATIOS: '/accounting/ratios',
    PERIODS: '/accounting/periods',
    FIXED_ASSETS: '/accounting/fixed-assets',
    SETTINGS: '/accounting/settings',
  },
  PLATFORM: {
    INDEX: '/platform',
    OVERVIEW: '/platform/overview',
    BUSINESSES: '/platform/businesses',
    USERS: '/platform/users',
    ROLES: '/platform/roles',
    SENT_MESSAGES: '/platform/sent-messages',
    GUIDE: {
      INDEX: '/platform/guide',
      TUTORIALS: '/platform/guide/tutorials',
      FAQS: '/platform/guide/faqs',
      FEEDBACK: '/platform/guide/feedback',
    },
  },
} as const;
